"""empty message

Revision ID: 7e467aae8f75
Revises: 3be2cad8f098
Create Date: 2023-05-23 19:26:24.738239

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7e467aae8f75"
down_revision = "3be2cad8f098"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.alter_column("data", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=False)
        batch_op.create_foreign_key(None, "quizzes", ["quiz_id"], ["id"])

    with op.batch_alter_table("quiz_scores", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "quizzes", ["quiz_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quiz_scores", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("data", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=True)

    # ### end Alembic commands ###
