[tool.ruff]
line-length = 200
target-version = "py311"
select = ["E", "F", "I", "UP"]
ignore = ["D203"]
show-source = true

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.pylint.messages_control]
disable = "C0114,C0115,C0116"

[tool.pytest.ini_options]
addopts = "-ra --cov=src"
pythonpath = ["src"]
env_files = ['.env']
