[tool.ruff]
line-length = 120
target-version = "py38"
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = ["D203"]

[tool.black]
line-length = 120
target-version = ["py38"]

[tool.pylint.messages_control]
disable = "C0114,C0115,C0116"

[tool.pytest.ini_options]
addopts = "-ra --cov=src --browser=firefox"
pythonpath = ["src"]
env_files = ['.env']

[tool.coverage.report]
show_missing = true
fail_under = 100
